; ============================================================
; ESP-NOW AMI Waveform Project
; ============================================================

[platformio]
default_envs = master
src_dir = src

; ---- Shared base config ----
[env]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32s3
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
build_flags = 
    -DBOARD_HAS_PSRAM
    ;-DARDUINO_USB_MODE=1
    ;-DARDUINO_USB_CDC_ON_BOOT=1

; ---- Master ----
[env:master]
build_src_filter = -<*> +<master/>

; ---- Slave 1 ----
[env:slave1]
build_src_filter = -<*> +<slave/>
build_flags =
    ${env.build_flags}
    -DSLAVE_ID=1
    -DMASTER_MAC_B0=0xE4
    -DMASTER_MAC_B1=0xB3
    -DMASTER_MAC_B2=0x23
    -DMASTER_MAC_B3=0xF7
    -DMASTER_MAC_B4=0xF6
    -DMASTER_MAC_B5=0x74


; ---- Slave 2 ----
[env:slave2]
build_src_filter = -<*> +<slave/>
build_flags =
    ${env.build_flags}
    -DSLAVE_ID=2
    -DMASTER_MAC_B0=0xE4
    -DMASTER_MAC_B1=0xB3
    -DMASTER_MAC_B2=0x23
    -DMASTER_MAC_B3=0xF7
    -DMASTER_MAC_B4=0xF6
    -DMASTER_MAC_B5=0x74


; ---- ESP32-S3 Supermini ----
[env:supermini]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Configurações exatas para o chip ESP32S3FH4R2 (Supermini)
board_build.mcu = esp32s3
board_upload.flash_size = 4MB
board_build.partitions = default.csv
board_build.flash_mode = dio
board_build.arduino.memory_type = qio_qspi

; Seleciona qual código vai rodar nela (assumindo que seja o master)
build_src_filter = -<*> +<master/> 

build_flags = 
    -DBOARD_HAS_PSRAM
    ; As duas linhas abaixo são VITAIS para o Supermini
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
